 DROP TABLE IF EXISTS BOUNDARY;
 DROP TABLE IF EXISTS BOUNDARY_TYPE;
 DROP TABLE IF EXISTS BOUNDARY_STATUS;

 CREATE TABLE BOUNDARY_TYPE
(ID INT auto_increment PRIMARY KEY,
 CODE VARCHAR(40) NOT NULL,
 LEVEL SMALLINT NOT NULL,
 DISPLAY_VALUE VARCHAR(512) NOT NULL,
 ACTIVE BOOLEAN NOT NULL,
 DESCRIPTION VARCHAR(2048));

CREATE UNIQUE INDEX BOUNDARY_TYPE_IDX ON BOUNDARY_TYPE(CODE);

 CREATE TABLE BOUNDARY_STATUS
(ID INT auto_increment PRIMARY KEY,
 CODE VARCHAR(40) NOT NULL,
 DISPLAY_VALUE VARCHAR(512) NOT NULL,
 ACTIVE BOOLEAN NOT NULL,
 DESCRIPTION VARCHAR(2048));

CREATE UNIQUE INDEX BOUNDARY_STATUS_IDX ON BOUNDARY_STATUS(CODE);

CREATE TABLE BOUNDARY
(ID VARCHAR(40) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
TYPE_CODE VARCHAR(40) NOT NULL,
AUTHORITY_NAME VARCHAR(255),
PARENT_ID VARCHAR(40),
RECORDER_NAME VARCHAR(255),
GEOM VARCHAR(100000),
STATUS_CODE VARCHAR(40) DEFAULT 'pending',
PROCESSED BOOLEAN DEFAULT TRUE,
VERSION INT DEFAULT 0,
FOREIGN KEY (STATUS_CODE) REFERENCES BOUNDARY_STATUS(CODE),
FOREIGN KEY (TYPE_CODE) REFERENCES BOUNDARY_TYPE(CODE),
FOREIGN KEY (PARENT_ID) REFERENCES BOUNDARY(ID)
);

ALTER TABLE CLAIM ADD COLUMN IF NOT EXISTS BOUNDARY_ID VARCHAR(40);
ALTER TABLE CLAIM ADD FOREIGN KEY (BOUNDARY_ID) REFERENCES BOUNDARY(ID);

MERGE INTO CLAIM_STATUS(STATUS) KEY (STATUS) SELECT 'issued' FROM DUAL;

UPDATE CONFIGURATION SET VALUE='1.7.0' WHERE NAME='DBVERSION' AND VALUE='1.6.0';
UPDATE CONFIGURATION SET VALUE='1.1' WHERE NAME='PROTOVERSION' AND VALUE='1.0';
