ALTER TABLE CLAIM ALTER COLUMN NAME SET NULL;
ALTER TABLE CLAIM ALTER COLUMN PERSON_ID SET NULL;
ALTER TABLE CLAIM ADD CREATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0);

UPDATE CONFIGURATION SET "VALUE"='1.9.0' WHERE NAME='DBVERSION' AND "VALUE"='1.8.0';

