ALTER TABLE LANGUAGE DROP COLUMN ID;
ALTER TABLE LANGUAGE ADD PRIMARY KEY (CODE);
DROP INDEX IF EXISTS LANGUAGE_IDX;

ALTER TABLE CLAIM_TYPE DROP COLUMN ID;
ALTER TABLE CLAIM_TYPE ADD PRIMARY KEY (CODE);
DROP INDEX IF EXISTS CLAIM_TYPE_IDX;

ALTER TABLE DOCUMENT_TYPE DROP COLUMN ID;
ALTER TABLE DOCUMENT_TYPE ADD PRIMARY KEY (CODE);
DROP INDEX IF EXISTS DOCUMENT_TYPE_IDX;

ALTER TABLE BOUNDARY_STATUS DROP COLUMN ID;
ALTER TABLE BOUNDARY_STATUS ADD PRIMARY KEY (CODE);
DROP INDEX IF EXISTS BOUNDARY_STATUS_IDX;

ALTER TABLE BOUNDARY_TYPE DROP COLUMN ID;
ALTER TABLE BOUNDARY_TYPE ADD PRIMARY KEY (CODE);
DROP INDEX IF EXISTS BOUNDARY_TYPE_IDX;

ALTER TABLE PERSON ADD ID_TYPE_TMP VARCHAR(255);
UPDATE PERSON SET ID_TYPE_TMP = ID_TYPE;
ALTER TABLE PERSON DROP COLUMN ID_TYPE;
ALTER TABLE PERSON ALTER COLUMN ID_TYPE_TMP RENAME TO ID_TYPE;

ALTER TABLE ID_TYPE DROP COLUMN ID;
ALTER TABLE ID_TYPE ALTER COLUMN TYPE RENAME TO CODE;
ALTER TABLE ID_TYPE ADD PRIMARY KEY (CODE);
DROP INDEX IF EXISTS ID_TYPE_IDX;
ALTER TABLE PERSON ADD CONSTRAINT FK_PERSON_ID_TYPE FOREIGN KEY (ID_TYPE) REFERENCES ID_TYPE(CODE) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE CLAIM ADD LAND_USE_TMP VARCHAR(255);
UPDATE CLAIM SET LAND_USE_TMP = LAND_USE;
ALTER TABLE CLAIM DROP COLUMN LAND_USE;
ALTER TABLE CLAIM ALTER COLUMN LAND_USE_TMP RENAME TO LAND_USE;

ALTER TABLE LAND_USE DROP COLUMN ID;
ALTER TABLE LAND_USE ALTER COLUMN TYPE RENAME TO CODE;
ALTER TABLE LAND_USE ADD PRIMARY KEY (CODE);
DROP INDEX IF EXISTS LAND_USE_IDX;
ALTER TABLE CLAIM ADD CONSTRAINT FK_CLAIM_LAND_USE FOREIGN KEY (LAND_USE) REFERENCES LAND_USE(CODE) ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE PROJECT (
	ID                   VARCHAR(40)  NOT NULL  ,
	DISPLAY_NAME         VARCHAR(5000)  NOT NULL  ,
	BOUNDARY             VARCHAR(20000)    ,
	TILES_SERVER_TYPE    VARCHAR(100)    ,
	TILES_LAYER_NAME     VARCHAR(100)    ,
	TILES_SERVER_URL     VARCHAR(500)    ,
	GEOM_REQUIRED        BOOLEAN   DEFAULT TRUE ,
	ACTIVE               BOOLEAN   DEFAULT TRUE ,
	LANGUAGE_CODE        VARCHAR(20)   DEFAULT 'en-US' ,
	CONSTRAINT PK_PROJECT_ID PRIMARY KEY ( ID )
 );
COMMENT ON TABLE PROJECT IS 'Survey projects';

CREATE TABLE USER_LAYER (
	ID                   VARCHAR(40)  NOT NULL  ,
	DISPLAY_NAME         VARCHAR(500)  NOT NULL  ,
	FILE_PATH            VARCHAR(500)  NOT NULL  ,
	LAYER_ORDER          INTEGER  NOT NULL DEFAULT 1 ,
	ENABLED              BOOLEAN  NOT NULL DEFAULT TRUE ,
	CONSTRAINT PK_USER_LAYERS_ID PRIMARY KEY ( ID )
);
ALTER TABLE CLAIM ADD PROJECT_ID VARCHAR(40);
ALTER TABLE BOUNDARY ADD PROJECT_ID VARCHAR(40);

MERGE INTO CONFIGURATION(CONFIGURATION_ID, NAME, VALUE) KEY (CONFIGURATION_ID) SELECT '2', 'PROTOVERSION', '1.2' FROM DUAL;
UPDATE CONFIGURATION SET VALUE='2.0.0' WHERE NAME='DBVERSION' AND VALUE='1.9.0';

