SELECT SCRIPT FROM
(

/*

LIST ALL AVAILABLE UPGRADE SCRIPTS HERE AS FOLLOWS

*/

SELECT '0.1.0' as VERSION_FROM, '0.5.0' as VERSION_TO,'upgradedb_0.1.0_0.5.0.sql' as SCRIPT FROM DUAL
UNION
SELECT '0.5.0' as VERSION_FROM, '1.0.0' as VERSION_TO,'upgradedb_0.5.0_1.0.0.sql' as SCRIPT FROM DUAL
UNION 
SELECT '1.0.0' as VERSION_FROM, '1.1.0' as VERSION_TO,'upgradedb_1.0.0_1.1.0.sql' as SCRIPT FROM DUAL
UNION 
SELECT '1.1.0' as VERSION_FROM, '1.2.0' as VERSION_TO,'upgradedb_1.1.0_1.2.0.sql' as SCRIPT FROM DUAL
UNION 
SELECT '1.2.0' as VERSION_FROM, '1.3.0' as VERSION_TO,'upgradedb_1.2.0_1.3.0.sql' as SCRIPT FROM DUAL
UNION 
SELECT '1.3.0' as VERSION_FROM, '1.4.0' as VERSION_TO,'upgradedb_1.3.0_1.4.0.sql' as SCRIPT FROM DUAL
)
WHERE VERSION_FROM >= SELECT VALUE FROM CONFIGURATION CFG WHERE CFG.NAME='DBVERSION'
ORDER BY VERSION_FROM